name: 👀 Detect public API changes

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      new:
        description: 'Branch/tag of the new/updated version'
        required: true
      old:
        description: 'Branch/tag of the old/comparison version'
        required: true
      
jobs:

  build:
    runs-on: macos-26

    steps:
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
        
    - name: 🚚 Fetch repo
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: 👾 Define Diff Versions
      run: |
        if ! git check-ref-format --branch "$SOURCE" > /dev/null || ! git check-ref-format --branch "$TARGET" > /dev/null; then
          echo "Source and target must be valid branch or tag names."
          exit 1
        fi

        NEW="${SOURCE}~${HEAD_GITHUB_REPO}"
        OLD="${TARGET}~${BASE_GITHUB_REPO}"
        
        if [[ "$TARGET_BRANCH_NAME" == release/* ]]
        then
            LATEST_TAG=$(git describe --tags --abbrev=0)
            OLD="$LATEST_TAG~$BASE_GITHUB_REPO"
        fi
        
        # Providing the output to the environment
        echo "OLD_VERSION=$OLD" >> $GITHUB_ENV
        echo "NEW_VERSION=$NEW" >> $GITHUB_ENV
      env:
        SOURCE: ${{ github.event.inputs.new || github.head_ref }}
        TARGET: ${{ github.event.inputs.old || github.event.pull_request.base.ref }}
        HEAD_GITHUB_REPO: ${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name || github.repository }}.git
        BASE_GITHUB_REPO: ${{ github.server_url }}/${{ github.repository }}.git
        TARGET_BRANCH_NAME: ${{ github.head_ref || 'no target branch' }}

    # The github action automatically posts on a PR (if it's not a fork-PR)
    # and/or outputs the diff to the $GITHUB_STEP_SUMMARY
    - name: 🔍 Detect Changes
      uses: Adyen/adyen-swift-public-api-diff@0.10.1
      with:
        platform: "iOS"
        new: ${{ env.NEW_VERSION }}
        old: ${{ env.OLD_VERSION }}
