name: Publish AdyenNetworking.podspec

on:
  workflow_dispatch:
  workflow_call:
  
jobs:

  publish:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'

    - name: Publish Adyen.podspec
      run: |
        gem install cocoapods
        pod trunk push AdyenNetworking.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
