name: Test Cocoapods Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - main
    - develop

jobs:

  pods:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
        
    - name: Test Cocoapods Integration
      run: |
        brew update
        brew install xcodegen
        gem install cocoapods -v 1.10.2
        pod repo update
        pod lib lint AdyenNetworking.podspec --allow-warnings --verbose
        Scripts/test-CocoaPods-integration.sh
