name: Test Carthage Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - main
    - develop

jobs:

  carthage:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
        
    - name: Resolve dependencies
      run: |
        brew update
        brew install xcodegen
        brew upgrade carthage

    - name: Test Carthage Integration
      run: |
        carthage version
        Scripts/test-carthage-integration.sh
